---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: artifactory
  namespace: stuff
spec:
  releaseName: artifactory 
  chart:
    repository: https://charts.jfrog.io
    name: artifactory
    version: 10.3.1
  valueFileSecrets:
    # the redis-auth secret contains the password value
    - name: redis-auth
  values:
    #image.repository=docker.bintray.io/jfrog/artifactory-oss
    image:
      repository: docker.bintray.io/jfrog/artifactory-oss
